language: android

jdk: oraclejdk8

android:
 components:
 - platform-tools # ADB
 - tools #실제 안드로이드 SDK
 - build-tools-25.0.1 # 빌드 툴 버전
 - android-25
 - extra-android-m2repository # 라이브러리 maven Repository 에서 참고

before_install:
 - chmod +x gradlew

script: ./gradlew build